# Structure of a Data Analysis

Using the **kernlab** package, we would be able to obtain cleaned spam data.

```{r setting up}
library(kernlab)
data(spam)
dim(spam)
```

## Subsampling our data set

```{r subsampling}
set.seed(3435)
trainIndicator = rbinom(dim(spam)[1], size=1, prob=0.5)
table(trainIndicator)

trainSpam = spam[trainIndicator==1,]
testSpam = spam[trainIndicator==0,]
dim(trainSpam)
```

## Looking at summaries of the data

```{r summaries}
names(trainSpam)
head(trainSpam)
table(trainSpam$type)
```

## Plots

```{r plot}
plot(trainSpam$capitalAve ~ trainSpam$type)
plot(log10(trainSpam$capitalAve + 1) ~ trainSpam$type)
plot(log10(trainSpam[, 1:4] + 1))
```

## Clustering

```{r clustering}
hCluster = hclust(dist(t(trainSpam[, 1:57])))
plot(hCluster)
hClusterUpdated = hclust(dist(t(log10(trainSpam[, 1:55] + 1))))
plot(hClusterUpdated)
```

## Statistical prediction/modeling

```{r prediction/modeling}
trainSpam$numType = as.numeric(trainSpam$type) - 1
costFunction = function(x, y) {
  sum(x != (y > 0.5))
}
cvError = rep(NA, 55)
library(boot)
for (i in 1:55) {
  lmFormula = as.formula(paste("numType~", names(trainSpam)[i], sep  = ""))
  glmFit = glm(lmFormula, family = "binomial", data = trainSpam)
  cvError[i] = cv.glm(trainSpam, glmFit, costFunction, 2)$delta[2]
}
predictionModel = glm(numType ~ charDollar, family = "binomial", data = trainSpam)
predictionTest = predict(predictionModel, testSpam)
predictedSpam = rep("nonspam", dim(testSpam)[1])
predictedSpam[predictionModel$fitted > 0.5] = "spam"
result = table(predictedSpam, testSpam$type)
errorRate = (result[2] + result[3]) / (sum(result)) * 100
```

Error rate of `r errorRate`